package mixzpoker.domain.game.poker

import io.circe.{Decoder, Encoder}
import io.circe.generic.semiauto.{deriveDecoder, deriveEncoder}
import mixzpoker.domain.game.{GameEventId, GameId}
import mixzpoker.domain.user.UserId

final case class PokerEventContext(
  id: GameEventId,
  gameId: GameId,
  userId: Option[UserId],  // no user Id for the events generated by game
  event: PokerEvent
)

object PokerEventContext {
  implicit val pecEncoder: Encoder[PokerEventContext] = deriveEncoder
  implicit val pecDecoder: Decoder[PokerEventContext] = deriveDecoder
}